language: python

python:
    - "2.7"
    - "3.5"

sudo: false

env:
    - TOX_ENV=django18
    - TOX_ENV=django19
    - TOX_ENV=django110
    - TOX_ENV=djangomaster

matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=djangomaster

addons:
  apt:
    packages:
    - xmlsec1

install:
    - pip install --upgrade pip setuptools tox virtualenv

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV,TRAVIS_PYTHON_VERSION

notifications:
    email: false
